apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-words
  labels:
    app: reverse-words
spec:
  template:
    spec:
      containers:
      - name: reverse-words
        image: quay.io/cstark/tekton-reversewords:cb124440057506c993d967483df2bd2f26360117
        env:
        - name: RELEASE
          value: "Stage Release"
        - $patch: replace
